In [2]:
#Import packages
import pandas as pd

#Read in data
df = pd.read_csv("geno-pheno.dataset.tsv", sep = "\t")

df.head()

/tmp/ipykernel_9809/2676976629.py:5: DtypeWarning: Columns (0: AZT, 1: DDCFoldMatch, 2: TAFFoldMatch) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("geno-pheno.dataset.tsv", sep = "\t")

,RefID,IsolateID,IsolateName,Species,Type,PtID,Method,3TC,3TCFoldMatch,ABC,...,P291,P292,P293,P294,P295,P296,P297,P298,P299,P300
0,756,9918,CA9918,HIV1,Clinical,1391.0,PhenoSense,200.0,>,4.6,...,-,-,-,-,-,-,-,-,-,-
1,756,3832,CA3832,HIV1,Clinical,1433.0,PhenoSense,200.0,>,8.8,...,-,-,.,.,.,.,.,.,.,.
2,756,10464,CA10464,HIV1,Clinical,634.0,PhenoSense,200.0,>,14.0,...,.,.,.,.,.,.,.,.,.,.
3,756,9928,CA9928,HIV1,Clinical,637.0,PhenoSense,200.0,>,6.7,...,-,-,V,-,-,-,K,-,-,-
4,756,4372,CA4372,HIV1,Clinical,1274.0,PhenoSense,200.0,>,7.1,...,-,-,V,-,-,-,-,-,-,-

In [3]:
##Cleaning the data set
df_clean = df.copy()
df_clean.head()

,RefID,IsolateID,IsolateName,Species,Type,PtID,Method,3TC,3TCFoldMatch,ABC,...,P291,P292,P293,P294,P295,P296,P297,P298,P299,P300
0,756,9918,CA9918,HIV1,Clinical,1391.0,PhenoSense,200.0,>,4.6,...,-,-,-,-,-,-,-,-,-,-
1,756,3832,CA3832,HIV1,Clinical,1433.0,PhenoSense,200.0,>,8.8,...,-,-,.,.,.,.,.,.,.,.
2,756,10464,CA10464,HIV1,Clinical,634.0,PhenoSense,200.0,>,14.0,...,.,.,.,.,.,.,.,.,.,.
3,756,9928,CA9928,HIV1,Clinical,637.0,PhenoSense,200.0,>,6.7,...,-,-,V,-,-,-,K,-,-,-
4,756,4372,CA4372,HIV1,Clinical,1274.0,PhenoSense,200.0,>,7.1,...,-,-,V,-,-,-,-,-,-,-

### Exploratory data analysis

In [25]:
#DRop columns we don't need in the training
df_clean = df.drop(columns = ["RefID","Species","Type", "Method", "NNRTIDRMs", 'CompleteMutationListAvailable', 'Author','NonDRMs', 'Author','RefYear', 'MedlineID', 'Title',  'PtID', 'IsolateName'])
df_clean.head(n = 300)

#Remove Protease positions

df_clean = df_clean.loc[:, ~df_clean.columns.str.match(r"^P\d+$")]
df_clean.head()
df_clean.shape

(2505, 22)

In [26]:
# Explore the data
#df_clean.describe()

#df_clean.info()

df_clean.columns

df_clean.shape

(2505, 22)

In [23]:
# Find reverse transcriptase columns
[col for col in df_clean.columns if "RT" in col.upper()]

['NRTIDRMs']

In [27]:
#Check which columns retained
df_clean.columns

Index(['IsolateID', '3TC', '3TCFoldMatch', 'ABC', 'ABCFoldMatch', 'AZT',
       'AZTFoldMatch', 'D4T', 'D4TFoldMatch', 'DDC', 'DDCFoldMatch', 'DDI',
       'DDIFoldMatch', 'FTC', 'FTCFoldMatch', 'ISL', 'ISLFoldMatch', 'TAF',
       'TAFFoldMatch', 'TDF', 'TDFFoldMatch', 'NRTIDRMs'],
      dtype='str')

In [28]:
#View data 
df_clean.head()

,IsolateID,3TC,3TCFoldMatch,ABC,ABCFoldMatch,AZT,AZTFoldMatch,D4T,D4TFoldMatch,DDC,...,DDIFoldMatch,FTC,FTCFoldMatch,ISL,ISLFoldMatch,TAF,TAFFoldMatch,TDF,TDFFoldMatch,NRTIDRMs
0,9918,200.0,>,4.6,=,0.6,=,1.0,=,2.2,...,=,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M184V
1,3832,200.0,>,8.8,=,3.2,=,1.9,=,2.9,...,=,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"M41L, L74LV, M184V, L210W, T215Y"
2,10464,200.0,>,14.0,=,307,=,6.4,=,5.4,...,=,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"M41L, E44A, D67N, T69D, M184V, L210W, T215Y"
3,9928,200.0,>,6.7,=,6.5,=,1.6,=,2.2,...,=,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"M41L, M184V, T215Y"
4,4372,200.0,>,7.1,=,0.8,=,1.3,=,2.8,...,=,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"D67N, K70G, M184V, T215F, K219Q"

In [32]:
#Identifying unique mutations in the dataset

print(df_clean["NRTIDRMs"].unique())

<StringArray>
[                                                    'M184V',
                          'M41L, L74LV, M184V, L210W, T215Y',
               'M41L, E44A, D67N, T69D, M184V, L210W, T215Y',
                                        'M41L, M184V, T215Y',
                           'D67N, K70G, M184V, T215F, K219Q',
                                  'D67N, K70R, M184V, K219Q',
        'E40F, M41L, D67N, V75M, M184V, L210W, T215Y, K219Q',
         'M41L, D67N, T69D, K70R, V75M, M184V, T215F, K219W',
                                 'M41L, M184V, L210W, T215Y',
                           'M41L, L74V, M184V, L210W, T215Y',
 ...
 'M41L, E44D, D67N, T69D, L74V, M184V, L210W, T215Y, K219KN',
           'M41ML, D67N, K70R, M184V, L210LW, T215F, K219EG',
                                 'D67N, M184V, T215C, K219E',
                                              'K70R, T215TA',
             'M41L, D67N, K70R, V75VIM, L210W, T215Y, K219E',
         'M41L, E44D, D67N, K70R, L74V, L210W, T215Y, K219Q',
                           'M41L, V75M, F77L, M184V, T215FY',
        'M41L, E44A, T69D, L74V, M184V, L210W, T215Y, K219R',
             'M41L, E44A, T69D, M184MV, L210W, T215Y, K219R',
     'M41L, E44D, D67N, T69AD, M184MV, L210W, T215Y, K219KR']
Length: 1087, dtype: str

In [34]:
# Number of duplicate IsolateIDs
print("Duplicate IsolateIDs:", df_clean["IsolateID"].duplicated().sum())

Duplicate IsolateIDs: 0

In [38]:
missing = (df_clean.isnull().sum().to_frame(name="Missing"))

missing["Percent"] = round(missing["Missing"] / len(df_clean) * 100, 2)

missing.sort_values("Percent", ascending=False)

              Missing  Percent
ISLFoldMatch     2473    98.72
ISL              2473    98.72
TAF              2409    96.17
TAFFoldMatch     2409    96.17
DDCFoldMatch     2036    81.28
DDC              2003    79.96
FTC              1948    77.76
FTCFoldMatch     1948    77.76
NRTIDRMs          512    20.44
TDF               493    19.68
TDFFoldMatch      493    19.68
ABCFoldMatch      308    12.30
ABC               274    10.94
3TCFoldMatch      176     7.03
D4TFoldMatch      162     6.47
DDIFoldMatch      162     6.47
AZTFoldMatch      158     6.31
3TC               146     5.83
DDI               128     5.11
D4T               128     5.11
AZT               124     4.95
IsolateID           0     0.00

In [40]:
drug_cols = ["3TC", "ABC", "AZT", "D4T", "DDC", "DDI", "FTC", "ISL", "TAF", "TDF"]

available = df_clean[drug_cols].notna().sum().sort_values(ascending=False)

print(available)

AZT    2381
D4T    2377
DDI    2377
3TC    2359
ABC    2231
TDF    2012
FTC     557
DDC     502
TAF      96
ISL      32
dtype: int64